In [226]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import datetime

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Load the training data into feature matrix, class labels, and event ids:

In [227]:
from proj1_helpers import *
from implementations import *

# Use your own path here!
DATA_TRAIN_PATH = '/Users/jiaanzhu/Desktop/MLProject1/train.csv' # TODO: download train data and supply path here 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

In [223]:
#Replace -999.0 with mean of each column
#tx = np.where(tX != -999, tX, np.nan)  # Replace -999 with nan
#tx = np.where(np.isnan(tx), np.ma.array(tx, mask=np.isnan(tx)).mean(axis=0), tx) 
tx = np.where(tX == -999, np.ma.array(tX, mask= (tX == -999)).mean(axis=0), tX) 
# Remove columns contain -999
# tx = tX[:, ~np.any(tX == -999, axis=0)

In [240]:
# Define the parameters of the algorithm.
max_iters = 10000
gamma = 0.000001

# Initialization
w_initial = np.zeros(tx.shape[1])

# Start gradient descent.
start_time = datetime.datetime.now()
gradient_losses, gradient_ws = gradient_descent(y, tx, w_initial, max_iters, gamma)
end_time = datetime.datetime.now()

# Print result
exection_time = (end_time - start_time).total_seconds()
print("Gradient Descent: execution time={t:.3f} seconds".format(t=exection_time))


Gradient Descent: execution time=189.785 seconds


In [237]:
# Define the parameters of the algorithm.
max_iters = 5000
gamma = 0.00000005
batch_size = 1

# Initialization
w_initial = np.zeros(tx.shape[1])

# Start SGD.
start_time = datetime.datetime.now()
sgd_losses, sgd_ws = stochastic_gradient_descent(
    y, tx, w_initial, batch_size, max_iters, gamma)
end_time = datetime.datetime.now()

# Print result
exection_time = (end_time - start_time).total_seconds()
print("SGD: execution time={t:.3f} seconds".format(t=exection_time))


SGD: execution time=347.962 seconds


In [242]:
weights = gradient_ws[-1]
print(weights) 
print(gradient_losses) # Show changes in losses


[ 5.90549078e-04 -9.58116008e-03 -1.57468699e-03 -1.87386785e-05
  2.44737085e-05  6.45748734e-04 -4.81297826e-04  3.33753197e-04
 -1.09586701e-03  3.07880833e-03 -4.82771114e-04  9.13585130e-04
  9.82922197e-05  5.02659450e-03 -1.23013153e-05 -7.06457549e-05
  6.17499917e-05 -1.39671849e-05  5.37096929e-05  1.89511935e-03
  2.81289492e-05 -5.96090204e-04 -1.88086946e-04 -2.17920515e-03
  2.22606986e-06  1.88298148e-05 -5.24419198e-03  1.62330800e-05
 -2.00593225e-05 -2.00952830e-03]
[0.5, 0.48761870683578723, 0.4811087214156105, 0.4774776239325597, 0.47526149280305713, 0.4737441030722358, 0.47257498221241295, 0.47158257470926657, 0.4706828478755174, 0.4698345845826327, 0.4690175137997138, 0.46822161268696677, 0.46744187347128013, 0.46667574352606134, 0.46592187310117267, 0.4651795027157995, 0.46444816345543255, 0.4637275303325679, 0.4630173505221057, 0.4623174082237701, 0.4616275074419424, 0.4609474635307376, 0.4602770990273511, 0.4596162415836636, 0.45896472292481316, 0.4583223783106

In [239]:
weights = sgd_ws[-1]
print(weights)
print(sgd_losses) # Show changes in losses

[-8.41576310e-04 -2.83132095e-03 -6.65311568e-04  1.00625179e-03
 -6.33819292e-06  4.52943023e-04 -4.43990296e-05 -2.31134869e-05
 -3.72166259e-04  3.28625328e-04 -5.73101309e-05  6.14635208e-05
  3.84189881e-07  5.71298552e-04 -1.33489247e-06 -2.19604691e-06
 -7.34315886e-04  6.26337171e-07  7.34383236e-06 -5.32963771e-04
  5.44920676e-06 -2.77228008e-04  3.53267641e-06 -8.48309502e-04
 -1.46890831e-06  1.06891691e-05 -1.01214190e-03 -1.91767247e-07
 -3.59886527e-06  4.91644541e-04]
[0.5, 0.49820257016131614, 0.49457282116834056, 0.49700017965631266, 0.4986529601895378, 0.4961039964399033, 0.49371839808277, 0.49151847223003026, 0.49386262978888346, 0.4969184451320844, 0.49424354762597067, 0.49180800029693394, 0.4894232149576536, 0.488065790527284, 0.4863523858868199, 0.4846824244517783, 0.48636537518501144, 0.48501884064881573, 0.48380529374006037, 0.4825512201936444, 0.481205522508382, 0.4825551267383892, 0.4814320352748852, 0.4802340368879541, 0.4813983431378571, 0.48268202923839626

## Generate predictions and save ouput in csv format for submission:

In [243]:
# Use your own path here!
DATA_TEST_PATH = '/Users/jiaanzhu/Desktop/MLProject1/test.csv' # TODO: download train data and supply path here 
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [244]:
#Replace -999.0 with mean of each column
tx_test = np.where(tX_test == -999, np.ma.array(tX_test, mask= (tX_test == -999)).mean(axis=0), tX_test) 
# Remove columns contain -999
# tx_test = tX_test[:, ~np.any(tX_test == -999, axis=0)]

In [245]:
# Use your own path here!
OUTPUT_PATH = '/Users/jiaanzhu/Desktop/MLProject1/submission.csv' # TODO: fill in desired name of output file for submission
y_pred = predict_labels(weights, tx_test)
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)

In [ ]:
'''
Test codes below
'''

In [202]:
print(np.count_nonzero(tx == -999, axis=0)) # Show numbers of -999.0(NaN) in every column

[ 38114      0      0      0 177457 177457 177457      0      0      0
      0      0 177457      0      0      0      0      0      0      0
      0      0      0  99913  99913  99913 177457 177457 177457      0]


In [201]:
tx.shape

(250000, 30)

In [193]:
tx = tX[:, ~np.any(tX == -999, axis=0)] # Remove columns contain -999

In [22]:
print(np.count_nonzero(y == 1)) 

85667


In [246]:
tx_test.shape

(568238, 30)

In [247]:
print(np.count_nonzero(tx_test == -999, axis=0)) 

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [41]:
np.zeros(19)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

In [219]:
tx[0:5, :]

array([[ 1.38470000e+02,  5.16550000e+01,  9.78270000e+01,
         2.79800000e+01,  9.10000000e-01,  1.24711000e+02,
         2.66600000e+00,  3.06400000e+00,  4.19280000e+01,
         1.97760000e+02,  1.58200000e+00,  1.39600000e+00,
         2.00000000e-01,  3.26380000e+01,  1.01700000e+00,
         3.81000000e-01,  5.16260000e+01,  2.27300000e+00,
        -2.41400000e+00,  1.68240000e+01, -2.77000000e-01,
         2.58733000e+02,  2.00000000e+00,  6.74350000e+01,
         2.15000000e+00,  4.44000000e-01,  4.60620000e+01,
         1.24000000e+00, -2.47500000e+00,  1.13497000e+02],
       [ 1.60937000e+02,  6.87680000e+01,  1.03235000e+02,
         4.81460000e+01,  2.40373503e+00,  3.71783360e+02,
        -8.21688171e-01,  3.47300000e+00,  2.07800000e+00,
         1.25157000e+02,  8.79000000e-01,  1.41400000e+00,
         4.58289801e-01,  4.20140000e+01,  2.03900000e+00,
        -3.01100000e+00,  3.69180000e+01,  5.01000000e-01,
         1.03000000e-01,  4.47040000e+01, -1.91600000e+

In [221]:
tx[0:5, :]

array([[ 1.38470000e+02,  5.16550000e+01,  9.78270000e+01,
         2.79800000e+01,  9.10000000e-01,  1.24711000e+02,
         2.66600000e+00,  3.06400000e+00,  4.19280000e+01,
         1.97760000e+02,  1.58200000e+00,  1.39600000e+00,
         2.00000000e-01,  3.26380000e+01,  1.01700000e+00,
         3.81000000e-01,  5.16260000e+01,  2.27300000e+00,
        -2.41400000e+00,  1.68240000e+01, -2.77000000e-01,
         2.58733000e+02,  2.00000000e+00,  6.74350000e+01,
         2.15000000e+00,  4.44000000e-01,  4.60620000e+01,
         1.24000000e+00, -2.47500000e+00,  1.13497000e+02],
       [ 1.60937000e+02,  6.87680000e+01,  1.03235000e+02,
         4.81460000e+01,  2.40373503e+00,  3.71783360e+02,
        -8.21688171e-01,  3.47300000e+00,  2.07800000e+00,
         1.25157000e+02,  8.79000000e-01,  1.41400000e+00,
         4.58289801e-01,  4.20140000e+01,  2.03900000e+00,
        -3.01100000e+00,  3.69180000e+01,  5.01000000e-01,
         1.03000000e-01,  4.47040000e+01, -1.91600000e+

In [224]:
tx == ty

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [225]:
np.count_nonzero(tx == ty)

7500000

In [229]:
tx.shape[1]

30