In [106]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import datetime

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Load the training data into feature matrix, class labels, and event ids:

In [105]:
from proj1_helpers import *
from implementations import *

# Use your own path here!
DATA_TRAIN_PATH = '/Users/jiaanzhu/Desktop/MLProject1/train.csv' # TODO: download train data and supply path here 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

In [107]:
'''
#LOOK AT DATA
for i in range(tX.shape[1]):
    plt.figure()
    plt.plot(tX[:,i])
    plt.show()
'''
tx = tX.copy() # Make a copy of original data

In [ ]:
# Dealing with outliers below

In [ ]:
# Dealing with -999 below

In [108]:
# Replace -999.0 with mean of each column

tx = np.where(tX == -999, np.ma.array(tX, mask= (tX == -999)).mean(axis=0), tX) 

# Replace -999.0 with median of each column

'''
# Replace -999 with nan
tx = np.where(tX != -999, tX, np.nan)
# column median
col_median = np.nanmedian(tx, axis = 0)
# find indices where nan value is present 
inds_train = np.where(np.isnan(tx))
# replace inds with median of column 
tx[inds_train] = np.take(col_median, inds_train[1])
'''

# Remove columns contain -999

'''
# tx = tX[:, ~np.any(tX == -999, axis=0)]
'''

# Remove columns with number of NaNs > 50%, then replace -999.0 with mean of each column

'''
# remove_index = np.argwhere(np.count_nonzero(tX == -999, axis=0) > tX.shape[0]/2)
# tX2 = np.delete(tX, remove_index, 1)
# tx = np.where(tX2 == -999, np.ma.array(tX2, mask= (tX2 == -999)).mean(axis=0), tX2) 
'''

#extra code
# np.count_nonzero(tX == -999, axis=0)
# tx = np.where(tX != -999, tX, np.nan)  # Replace -999 with nan
# tx = np.where(np.isnan(tx), np.ma.array(tx, mask=np.isnan(tx)).mean(axis=0), tx)  # Replace nan with mean of each column

In [109]:
# Define the parameters of the algorithm.
max_iters = 10000
gamma = 0.0000001

# Initialization
w_initial = np.zeros(tx.shape[1])

# Start gradient descent.
start_time = datetime.datetime.now()
gradient_losses, gradient_ws = gradient_descent(y, tx, w_initial, max_iters, gamma)
end_time = datetime.datetime.now()

# Print result
exection_time = (end_time - start_time).total_seconds()
print("Gradient Descent: execution time={t:.3f} seconds".format(t=exection_time))


Gradient Descent: execution time=175.150 seconds


In [237]:
# Define the parameters of the algorithm.
max_iters = 5000
gamma = 0.00000005
batch_size = 1

# Initialization
w_initial = np.zeros(tx.shape[1])

# Start SGD.
start_time = datetime.datetime.now()
sgd_losses, sgd_ws = stochastic_gradient_descent(
    y, tx, w_initial, batch_size, max_iters, gamma)
end_time = datetime.datetime.now()

# Print result
exection_time = (end_time - start_time).total_seconds()
print("SGD: execution time={t:.3f} seconds".format(t=exection_time))


SGD: execution time=347.962 seconds


In [110]:
weights_sd = gradient_ws[-1] # Weights for gd
print(weights_sd) 
print(gradient_losses[-10:-1]) # Show changes in losses


[ 1.59378457e-04 -6.42214392e-03 -4.29387625e-04  2.12448443e-03
 -1.77910182e-05  6.40398423e-04 -9.28822399e-05 -2.09665312e-05
 -9.30198267e-04  8.22870919e-04 -1.44505930e-04  1.68940996e-04
  2.99724882e-06  2.12523248e-03 -8.94651856e-07 -7.74018637e-06
 -1.20231314e-03  5.02498428e-07  5.05587291e-06 -1.05195845e-03
  7.05964374e-06 -6.23229928e-04 -7.76648501e-06 -1.40535232e-03
  3.01976748e-07  2.58619697e-06 -2.12300084e-03  1.84506003e-06
 -2.26645671e-06 -1.00047361e-04]
[0.3731418161900824, 0.37314054622841036, 0.37313927655967793, 0.373138007183802, 0.37313673810070025, 0.3731354693102901, 0.3731342008124891, 0.37313293260721436, 0.3731316646943834]


In [249]:
weights_sgd = sgd_ws[-1] # Weights for sgd
print(weights)
print(sgd_losses[-10:-1]) # Show changes in losses

[ 5.90549078e-04 -9.58116008e-03 -1.57468699e-03 -1.87386785e-05
  2.44737085e-05  6.45748734e-04 -4.81297826e-04  3.33753197e-04
 -1.09586701e-03  3.07880833e-03 -4.82771114e-04  9.13585130e-04
  9.82922197e-05  5.02659450e-03 -1.23013153e-05 -7.06457549e-05
  6.17499917e-05 -1.39671849e-05  5.37096929e-05  1.89511935e-03
  2.81289492e-05 -5.96090204e-04 -1.88086946e-04 -2.17920515e-03
  2.22606986e-06  1.88298148e-05 -5.24419198e-03  1.62330800e-05
 -2.00593225e-05 -2.00952830e-03]
[0.4078056083708234, 0.4090425079685934, 0.4084078648552148, 0.4091488751615451, 0.40847047593963726, 0.407753567657346, 0.40850189190329494, 0.40945857141931796, 0.40880194023235056]


## Generate predictions and save ouput in csv format for submission:

In [111]:
# Use your own path here!
DATA_TEST_PATH = '/Users/jiaanzhu/Desktop/MLProject1/test.csv' # TODO: download train data and supply path here 
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [112]:
#Replace -999.0 with mean of each column
#tX_test2 = np.delete(tX_test, remove_index, 1)
tx_test = tX_test.copy() # Make a copy
# Replace -999 with nan
tx_test = np.where(tx_test != -999, tx_test, np.nan)
# find indices where nan value is present
inds_test = np.where(np.isnan(tx_test))
# replace inds with avg of column 
tx_test[inds_test] = np.take(col_median, inds_test[1])
# Remove columns contain -999
# tx_test = tX_test[:, ~np.any(tX_test == -999, axis=0)]

In [113]:
# Use your own path here!
OUTPUT_PATH = '/Users/jiaanzhu/Desktop/MLProject1/submission.csv' # TODO: fill in desired name of output file for submission
y_pred = predict_labels(weights_sd, tx_test) # Use deifferent weights here
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)

In [ ]:
'''
Test codes below
'''

In [39]:
print(np.count_nonzero(tX == -999, axis=0)) 

[ 38114      0      0      0 177457 177457 177457      0      0      0
      0      0 177457      0      0      0      0      0      0      0
      0      0      0  99913  99913  99913 177457 177457 177457      0]


In [201]:
tx.shape

(250000, 30)

In [297]:
tX2.shape

(250000, 28)

In [193]:
tx = tX[:, ~np.any(tX == -999, axis=0)] # Remove columns contain -999

In [22]:
print(np.count_nonzero(y == 1)) 

85667


In [246]:
tx_test.shape

(568238, 30)

In [45]:
print(np.count_nonzero(inds == -999, axis=0)) 

0


In [225]:
np.count_nonzero(tx == ty)

7500000

In [293]:
np.count_nonzero(tX == -999, axis=0)

array([ 38114,      0,      0,      0, 177457, 177457, 177457,      0,
            0,      0,      0,      0, 177457,      0,      0,      0,
            0,      0,      0,      0,      0,      0,      0,  99913,
        99913,  99913, 177457, 177457, 177457,      0])

In [294]:
np.count_nonzero(tX == -999, axis=0) > 125000

array([False, False, False, False,  True,  True,  True, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
        True,  True, False])

In [267]:
print(np.count_nonzero(tx_test == 2.4037350261224666, axis=0)) 

[     0      0      0      0 402796      0      0      0      0      0
      0      0      0      0      0      0      0      0      0      0
      0      0      0      0      0      0      0      0      0      0]


In [102]:
print(np.count_nonzero(tx == -999, axis=0)) 

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [46]:
inds

(array([     1,      1,      1, ..., 249999, 249999, 249999]),
 array([ 4,  5,  6, ..., 26, 27, 28]))

In [311]:
np.count_nonzero(tX == -999) > tX.shape[0]/2

True

In [333]:
tx_test.shape

(568238, 23)

In [55]:
# Initialising numpy array 
ini_array = np.array([[1.3, 2.5, 3.6, np.nan],  
                      [2.6, 3.3, np.nan, 5.5], 
                      [2.1, 3.2, np.nan, 6.5],
                      [1.0, 2.0, np.nan, 4.0]]) 
  
# printing initial array 
print ("initial array", ini_array) 
  
# column mean 
col_median = np.nanmedian(ini_array, axis = 0) 
  
# printing column mean 
print ("columns median", str(col_mean)) 
  
# find indices where nan value is present 
inds = np.where(np.isnan(ini_array)) 
  
# replace inds with avg of column 
ini_array[inds] = np.take(col_median, inds[1]) 
  
# printing final array 
print ("final array", ini_array) 

initial array [[1.3 2.5 3.6 nan]
 [2.6 3.3 nan 5.5]
 [2.1 3.2 nan 6.5]
 [1.  2.  nan 4. ]]
columns median [2.  3.  4.5 6. ]
final array [[1.3 2.5 3.6 5.5]
 [2.6 3.3 3.6 5.5]
 [2.1 3.2 3.6 6.5]
 [1.  2.  3.6 4. ]]


In [103]:
col_median

array([ 1.124060e+02,  4.652400e+01,  7.375200e+01,  3.846750e+01,
        2.107000e+00,  2.258850e+02, -2.440000e-01,  2.491500e+00,
        1.231550e+01,  1.206645e+02,  1.280000e+00, -3.560000e-01,
        4.540000e-01,  3.180400e+01, -2.300000e-02, -3.300000e-02,
        4.051600e+01, -4.500000e-02,  8.600000e-02,  3.480200e+01,
       -2.400000e-02,  1.797390e+02,  1.000000e+00,  6.556100e+01,
        0.000000e+00, -3.300000e-02,  4.790200e+01, -1.000000e-02,
       -2.000000e-03,  4.051250e+01])